name 'opcwls'
maintainer 'James Calise'
maintainer_email 'james.calise@oracle.com'
license 'all_rights'
description 'Installs/Configures WLS 12.2.1'
long_description 'Installs/Configures WLS 12.2.1'
version '0.1.0'

depends 'java'
depends 'firewall'
depends 'systemd'
depends 'chef-sugar'
