default['cloud']['storage_container'] = "Software"
default['cloud']['cloud_identity_domain'] = ""
default['cloud']['cloud_username'] = "cloud.admin"
default['cloud']['cloud_password'] = ""
default['cloud']['storage_url'] = "https://#{node['cloud']['cloud_identity_domain']}.storage.oraclecloud.com/v1/Storage-#{node['cloud']['cloud_identity_domain']}/SDLC_Pipeline_wksp/#{node['cloud']['storage_container']}"
#default['cloud']['storage_url'] = "https://em2.storage.oraclecloud.com/v1/Storage-gse00002056/SDLC_Pipeline_wksp/Software/"
